"""Create the Milestone 1 auditable truth layer

Revision ID: 0002_milestone_1_truth_layer
Revises: 0001_empty_baseline
Create Date: 2026-08-26
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_milestone_1_truth_layer"
down_revision: str | Sequence[str] | None = "0001_empty_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RELEASE_SCOPED_TABLES = (
    "release_source_snapshot",
    "release_lineage_snapshot",
    "release_assembly_membership",
    "assembly_taxon_assignment",
    "import_run",
    "eve_locus",
    "detection_call",
    "source_assessment",
    "import_ledger",
    "eve_locus_placement",
    "flank_assessment",
    "inclusion_decision",
    "release_locus_membership",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dataset_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset")),
        sa.UniqueConstraint("dataset_key", name=op.f("uq_dataset_dataset_key")),
    )
    op.create_table(
        "source_snapshot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_key", sa.String(length=255), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_version", sa.String(length=255), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("declared_manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("verified_manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("declared_license_key", sa.String(length=255), nullable=True),
        sa.Column("verified_license_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "declared_manifest_sha256 IS NULL OR declared_manifest_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_snapshot_valid_declared_manifest"),
        ),
        sa.CheckConstraint(
            "verified_manifest_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_snapshot_valid_verified_manifest"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshot")),
        sa.UniqueConstraint("snapshot_key", name=op.f("uq_source_snapshot_snapshot_key")),
    )
    op.create_table(
        "dataset_release",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column("release_key", sa.String(length=255), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'candidate'"), nullable=False
        ),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_release_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('published', 'deprecated') AND published_at IS NOT NULL "
            "AND manifest_sha256 IS NOT NULL) OR "
            "(status NOT IN ('published', 'deprecated') AND published_at IS NULL)",
            name=op.f("ck_dataset_release_publication_fields_match_status"),
        ),
        sa.CheckConstraint(
            "manifest_sha256 IS NULL OR manifest_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_dataset_release_valid_manifest_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'validated', 'published', 'deprecated', 'rejected')",
            name=op.f("ck_dataset_release_valid_status"),
        ),
        sa.CheckConstraint(
            "supersedes_release_id IS NULL OR supersedes_release_id <> id",
            name=op.f("ck_dataset_release_does_not_supersede_self"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id", "supersedes_release_id"],
            ["dataset_release.dataset_id", "dataset_release.id"],
            name="fk_dataset_release_supersedes_same_dataset",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
            name=op.f("fk_dataset_release_dataset_id_dataset"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_release")),
        sa.UniqueConstraint("dataset_id", "id", name="uq_dataset_release_dataset_id_id"),
        sa.UniqueConstraint("release_key", name=op.f("uq_dataset_release_release_key")),
    )
    op.create_table(
        "source_artifact",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("artifact_key", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("declared_sha256", sa.String(length=64), nullable=True),
        sa.Column("verified_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("declared_license_key", sa.String(length=255), nullable=True),
        sa.Column("verified_license_key", sa.String(length=255), nullable=False),
        sa.Column(
            "remote_checksum_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("remote_verification_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_verification_uri", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "declared_sha256 IS NULL OR declared_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_artifact_valid_declared_sha256"),
        ),
        sa.CheckConstraint(
            "verified_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_artifact_valid_verified_sha256"),
        ),
        sa.CheckConstraint(
            "NOT remote_checksum_verified OR "
            "(remote_verification_at IS NOT NULL "
            "AND remote_verification_uri IS NOT NULL)",
            name=op.f("ck_source_artifact_remote_verification_has_provenance"),
        ),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_source_artifact_nonnegative_byte_size")),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshot.id"],
            name=op.f("fk_source_artifact_snapshot_id_source_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_artifact")),
        sa.UniqueConstraint("artifact_key", name=op.f("uq_source_artifact_artifact_key")),
        sa.UniqueConstraint("snapshot_id", "id", name="uq_source_artifact_snapshot_id_id"),
        sa.UniqueConstraint(
            "snapshot_id", "verified_sha256", "filename", name="uq_source_artifact_snapshot_content"
        ),
    )
    op.create_table(
        "genome_assembly",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_key", sa.String(length=255), nullable=False),
        sa.Column(
            "namespace", sa.String(length=32), server_default=sa.text("'ncbi'"), nullable=False
        ),
        sa.Column("accession_version", sa.String(length=64), nullable=False),
        sa.Column("source_organism_name", sa.Text(), nullable=False),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accession_version ~ '^(GCA|GCF)_[0-9]+\\.[0-9]+$'",
            name=op.f("ck_genome_assembly_versioned_accession"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_genome_assembly_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genome_assembly")),
        sa.UniqueConstraint("assembly_key", name=op.f("uq_genome_assembly_assembly_key")),
        sa.UniqueConstraint(
            "namespace", "accession_version", name="uq_genome_assembly_namespace_accession"
        ),
    )
    op.create_table(
        "lineage_snapshot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_key", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("scheme_kind", sa.String(length=32), nullable=False),
        sa.Column("authority_namespace", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=False),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (domain = 'host' AND scheme_kind = 'study_defined')",
            name=op.f("ck_lineage_snapshot_host_snapshot_is_formal"),
        ),
        sa.CheckConstraint(
            "domain IN ('host', 'viral')", name=op.f("ck_lineage_snapshot_valid_domain")
        ),
        sa.CheckConstraint(
            "scheme_kind IN ('formal_taxonomy', 'study_defined')",
            name=op.f("ck_lineage_snapshot_valid_scheme_kind"),
        ),
        sa.CheckConstraint(
            "snapshot_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_lineage_snapshot_valid_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_lineage_snapshot_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineage_snapshot")),
        sa.UniqueConstraint(
            "domain",
            "scheme_kind",
            "authority_namespace",
            "version",
            name="uq_lineage_snapshot_authority_version",
        ),
        sa.UniqueConstraint(
            "id", "domain", "scheme_kind", name="uq_lineage_snapshot_id_domain_scheme"
        ),
        sa.UniqueConstraint("snapshot_key", name=op.f("uq_lineage_snapshot_snapshot_key")),
    )
    op.create_table(
        "release_source_snapshot",
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("source_snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["dataset_release.id"],
            name=op.f("fk_release_source_snapshot_release_id_dataset_release"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshot.id"],
            name=op.f("fk_release_source_snapshot_source_snapshot_id_source_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "source_snapshot_id", name=op.f("pk_release_source_snapshot")
        ),
        sa.UniqueConstraint("release_id", "role", name="uq_release_source_snapshot_role"),
    )
    op.create_table(
        "source_record",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_record_key", sa.String(length=255), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("worksheet", sa.Text(), nullable=False),
        sa.Column("row_number", sa.BigInteger(), nullable=False),
        sa.Column("native_vr_token", sa.String(length=255), nullable=False),
        sa.Column("assembly_accession_version", sa.String(length=64), nullable=False),
        sa.Column("sequence_accession_version", sa.String(length=128), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_payload_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "raw_payload_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_record_valid_payload_sha256"),
        ),
        sa.CheckConstraint("row_number > 0", name=op.f("ck_source_record_positive_row_number")),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "artifact_id"],
            ["source_artifact.snapshot_id", "source_artifact.id"],
            name="fk_source_record_artifact_same_snapshot",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_record")),
        sa.UniqueConstraint(
            "id", "snapshot_id", "native_vr_token", name="uq_source_record_id_snapshot_token"
        ),
        sa.UniqueConstraint("id", "snapshot_id", name="uq_source_record_id_snapshot"),
        sa.UniqueConstraint(
            "snapshot_id", "artifact_id", "worksheet", "row_number", name="uq_source_record_row"
        ),
        sa.UniqueConstraint(
            "snapshot_id",
            "assembly_accession_version",
            "sequence_accession_version",
            "native_vr_token",
            name="uq_source_record_occurrence",
        ),
        sa.UniqueConstraint("source_record_key", name=op.f("uq_source_record_source_record_key")),
    )
    op.create_table(
        "assembly_sequence",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_key", sa.String(length=255), nullable=False),
        sa.Column(
            "namespace", sa.String(length=32), server_default=sa.text("'insdc'"), nullable=False
        ),
        sa.Column("accession_version", sa.String(length=128), nullable=False),
        sa.Column("sequence_length", sa.BigInteger(), nullable=False),
        sa.Column("sequence_sha256", sa.String(length=64), nullable=True),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "accession_version ~ '^[A-Za-z0-9_]+\\.[0-9]+$'",
            name=op.f("ck_assembly_sequence_versioned_accession"),
        ),
        sa.CheckConstraint(
            "sequence_sha256 IS NULL OR sequence_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_assembly_sequence_valid_sha256"),
        ),
        sa.CheckConstraint(
            "sequence_length > 0", name=op.f("ck_assembly_sequence_positive_length")
        ),
        sa.ForeignKeyConstraint(
            ["assembly_id"],
            ["genome_assembly.id"],
            name=op.f("fk_assembly_sequence_assembly_id_genome_assembly"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_assembly_sequence_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assembly_sequence")),
        sa.UniqueConstraint(
            "assembly_id", "accession_version", name="uq_assembly_sequence_assembly_accession"
        ),
        sa.UniqueConstraint("assembly_id", "id", name="uq_assembly_sequence_assembly_id_id"),
        sa.UniqueConstraint("sequence_key", name=op.f("uq_assembly_sequence_sequence_key")),
    )
    op.create_table(
        "import_run",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("source_snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("importer_name", sa.String(length=255), nullable=False),
        sa.Column("importer_version", sa.String(length=128), nullable=False),
        sa.Column("code_sha256", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parameters_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'running' AND finished_at IS NULL) OR "
            "(status <> 'running' AND finished_at IS NOT NULL)",
            name=op.f("ck_import_run_finish_matches_status"),
        ),
        sa.CheckConstraint(
            "code_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_import_run_valid_code_sha256")
        ),
        sa.CheckConstraint(
            "parameters_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_import_run_valid_parameters_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_import_run_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "source_snapshot_id"],
            ["release_source_snapshot.release_id", "release_source_snapshot.source_snapshot_id"],
            name="fk_import_run_pinned_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "source_artifact_id"],
            ["source_artifact.snapshot_id", "source_artifact.id"],
            name="fk_import_run_artifact_same_snapshot",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_run")),
        sa.UniqueConstraint("id", "release_id", name="uq_import_run_id_release"),
        sa.UniqueConstraint("run_key", name=op.f("uq_import_run_run_key")),
    )
    op.create_table(
        "lineage_term",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("term_key", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("rank", sa.String(length=128), nullable=True),
        sa.Column("authority_local_id", sa.String(length=255), nullable=True),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["lineage_snapshot.id"],
            name=op.f("fk_lineage_term_snapshot_id_lineage_snapshot"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineage_term")),
        sa.UniqueConstraint("snapshot_id", "id", name="uq_lineage_term_snapshot_id_id"),
        sa.UniqueConstraint("snapshot_id", "term_key", name="uq_lineage_term_snapshot_key"),
    )
    op.create_table(
        "release_assembly_membership",
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "membership_role",
            sa.String(length=64),
            server_default=sa.text("'pilot_scope'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assembly_id"],
            ["genome_assembly.id"],
            name=op.f("fk_release_assembly_membership_assembly_id_genome_assembly"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["dataset_release.id"],
            name=op.f("fk_release_assembly_membership_release_id_dataset_release"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "assembly_id", name=op.f("pk_release_assembly_membership")
        ),
    )
    op.create_table(
        "release_lineage_snapshot",
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("scheme_kind", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "(role = 'assembly_source_taxonomy' AND domain = 'host' "
            "AND scheme_kind = 'formal_taxonomy') OR "
            "(role = 'formal_viral_taxonomy' AND domain = 'viral' "
            "AND scheme_kind = 'formal_taxonomy') OR "
            "(role = 'study_viral_lineage' AND domain = 'viral' "
            "AND scheme_kind = 'study_defined')",
            name=op.f("ck_release_lineage_snapshot_role_matches_namespace"),
        ),
        sa.CheckConstraint(
            "role IN ('assembly_source_taxonomy', 'formal_viral_taxonomy', 'study_viral_lineage')",
            name=op.f("ck_release_lineage_snapshot_valid_role"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["dataset_release.id"],
            name=op.f("fk_release_lineage_snapshot_release_id_dataset_release"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "domain", "scheme_kind"],
            ["lineage_snapshot.id", "lineage_snapshot.domain", "lineage_snapshot.scheme_kind"],
            name="fk_release_lineage_snapshot_namespace",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "snapshot_id", name=op.f("pk_release_lineage_snapshot")
        ),
        sa.UniqueConstraint("release_id", "role", name="uq_release_lineage_snapshot_role"),
        sa.UniqueConstraint(
            "release_id", "snapshot_id", "role", name="uq_release_lineage_snapshot_pair_role"
        ),
    )
    op.create_table(
        "assembly_taxon_assignment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assignment_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_role", sa.String(length=64), nullable=False),
        sa.Column("term_id", sa.BigInteger(), nullable=False),
        sa.Column("assignment_policy_key", sa.String(length=255), nullable=False),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "snapshot_role = 'assembly_source_taxonomy'",
            name=op.f("ck_assembly_taxon_assignment_requires_assembly_source_snapshot"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "assembly_id"],
            ["release_assembly_membership.release_id", "release_assembly_membership.assembly_id"],
            name="fk_assembly_taxon_assignment_release_assembly",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "snapshot_id", "snapshot_role"],
            [
                "release_lineage_snapshot.release_id",
                "release_lineage_snapshot.snapshot_id",
                "release_lineage_snapshot.role",
            ],
            name="fk_assembly_taxon_assignment_pinned_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "term_id"],
            ["lineage_term.snapshot_id", "lineage_term.id"],
            name="fk_assembly_taxon_assignment_term_same_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_assembly_taxon_assignment_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assembly_taxon_assignment")),
        sa.UniqueConstraint(
            "assignment_key", name=op.f("uq_assembly_taxon_assignment_assignment_key")
        ),
        sa.UniqueConstraint(
            "release_id",
            "assembly_id",
            "snapshot_id",
            "assignment_policy_key",
            name="uq_assembly_taxon_assignment_policy",
        ),
    )
    op.create_table(
        "eve_locus",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("locus_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_id", sa.BigInteger(), nullable=False),
        sa.Column("source_snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("source_record_id", sa.BigInteger(), nullable=False),
        sa.Column("native_vr_token", sa.String(length=255), nullable=False),
        sa.Column("identity_policy_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "locus_key ~ '^locus:eve:v1:sha256:[0-9a-f]{64}$'",
            name=op.f("ck_eve_locus_valid_locus_key"),
        ),
        sa.ForeignKeyConstraint(
            ["assembly_id", "sequence_id"],
            ["assembly_sequence.assembly_id", "assembly_sequence.id"],
            name="fk_eve_locus_sequence_same_assembly",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "assembly_id"],
            ["release_assembly_membership.release_id", "release_assembly_membership.assembly_id"],
            name="fk_eve_locus_release_assembly",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "source_snapshot_id"],
            ["release_source_snapshot.release_id", "release_source_snapshot.source_snapshot_id"],
            name="fk_eve_locus_pinned_snapshot",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "source_snapshot_id", "native_vr_token"],
            ["source_record.id", "source_record.snapshot_id", "source_record.native_vr_token"],
            name="fk_eve_locus_source_occurrence",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eve_locus")),
        sa.UniqueConstraint(
            "release_id",
            "id",
            "assembly_id",
            "sequence_id",
            name="uq_eve_locus_release_id_assembly_sequence",
        ),
        sa.UniqueConstraint("release_id", "id", name="uq_eve_locus_release_id_id"),
        sa.UniqueConstraint("release_id", "locus_key", name="uq_eve_locus_release_key"),
        sa.UniqueConstraint("release_id", "source_record_id", name="uq_eve_locus_source_record"),
        sa.UniqueConstraint(
            "release_id",
            "source_snapshot_id",
            "assembly_id",
            "sequence_id",
            "native_vr_token",
            "identity_policy_key",
            name="uq_eve_locus_source_occurrence",
        ),
    )
    op.create_table(
        "lineage_alias",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("term_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("normalized_alias", sa.Text(), nullable=False),
        sa.Column("alias_type", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), server_default=sa.text("'en'"), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "term_id"],
            ["lineage_term.snapshot_id", "lineage_term.id"],
            name="fk_lineage_alias_term_same_snapshot",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineage_alias")),
        sa.UniqueConstraint(
            "snapshot_id",
            "term_id",
            "normalized_alias",
            "alias_type",
            name="uq_lineage_alias_term_value",
        ),
    )
    op.create_table(
        "lineage_closure",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("ancestor_term_id", sa.BigInteger(), nullable=False),
        sa.Column("descendant_term_id", sa.BigInteger(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(depth = 0 AND ancestor_term_id = descendant_term_id) OR "
            "(depth > 0 AND ancestor_term_id <> descendant_term_id)",
            name=op.f("ck_lineage_closure_depth_matches_identity"),
        ),
        sa.CheckConstraint("depth >= 0", name=op.f("ck_lineage_closure_nonnegative_depth")),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "ancestor_term_id"],
            ["lineage_term.snapshot_id", "lineage_term.id"],
            name="fk_lineage_closure_ancestor_same_snapshot",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "descendant_term_id"],
            ["lineage_term.snapshot_id", "lineage_term.id"],
            name="fk_lineage_closure_descendant_same_snapshot",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_id", "ancestor_term_id", "descendant_term_id", name=op.f("pk_lineage_closure")
        ),
    )
    op.create_table(
        "detection_call",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("call_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("source_snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("source_record_id", sa.BigInteger(), nullable=False),
        sa.Column("locus_id", sa.BigInteger(), nullable=True),
        sa.Column("source_method_key", sa.String(length=255), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id", "locus_id"],
            ["eve_locus.release_id", "eve_locus.id"],
            name="fk_detection_call_locus_same_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id", "source_snapshot_id"],
            ["source_record.id", "source_record.snapshot_id"],
            name="fk_detection_call_source_record_snapshot",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_call")),
        sa.UniqueConstraint("release_id", "call_key", name="uq_detection_call_release_key"),
        sa.UniqueConstraint("release_id", "id", name="uq_detection_call_release_id_id"),
        sa.UniqueConstraint(
            "release_id", "source_record_id", name="uq_detection_call_source_record"
        ),
    )
    op.create_table(
        "eve_locus_placement",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("placement_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("locus_id", sa.BigInteger(), nullable=False),
        sa.Column("assembly_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_id", sa.BigInteger(), nullable=False),
        sa.Column("start0", sa.BigInteger(), nullable=False),
        sa.Column("end0", sa.BigInteger(), nullable=False),
        sa.Column("strand", sa.String(length=16), nullable=False),
        sa.Column("precision", sa.String(length=16), nullable=False),
        sa.Column(
            "coordinate_system",
            sa.String(length=32),
            server_default=sa.text("'0-based-half-open'"),
            nullable=False,
        ),
        sa.Column("raw_location", sa.Text(), nullable=True),
        sa.Column("raw_coordinate_system", sa.String(length=128), nullable=True),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("placement_sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "coordinate_system = '0-based-half-open'",
            name=op.f("ck_eve_locus_placement_canonical_coordinate_system"),
        ),
        sa.CheckConstraint(
            "placement_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_eve_locus_placement_valid_sha256")
        ),
        sa.CheckConstraint(
            "precision IN ('exact', 'approximate')",
            name=op.f("ck_eve_locus_placement_valid_precision"),
        ),
        sa.CheckConstraint(
            "strand IN ('+', '-', 'unknown')", name=op.f("ck_eve_locus_placement_valid_strand")
        ),
        sa.CheckConstraint(
            "start0 >= 0 AND start0 < end0", name=op.f("ck_eve_locus_placement_valid_interval")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "locus_id", "assembly_id", "sequence_id"],
            [
                "eve_locus.release_id",
                "eve_locus.id",
                "eve_locus.assembly_id",
                "eve_locus.sequence_id",
            ],
            name="fk_eve_locus_placement_locus_sequence",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_eve_locus_placement_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eve_locus_placement")),
        sa.UniqueConstraint(
            "id",
            "release_id",
            "locus_id",
            "precision",
            name="uq_eve_locus_placement_membership_ref",
        ),
        sa.UniqueConstraint(
            "id", "release_id", "locus_id", name="uq_eve_locus_placement_flank_ref"
        ),
        sa.UniqueConstraint("placement_key", name=op.f("uq_eve_locus_placement_placement_key")),
        sa.UniqueConstraint("release_id", "locus_id", name="uq_eve_locus_placement_locus"),
    )
    op.create_index(
        "ix_eve_locus_placement_exact_interval",
        "eve_locus_placement",
        ["release_id", "sequence_id", "start0", "end0"],
        unique=False,
        postgresql_where=sa.text("precision = 'exact'"),
    )
    op.create_table(
        "flank_assessment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assessment_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("locus_id", sa.BigInteger(), nullable=False),
        sa.Column("placement_id", sa.BigInteger(), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column(
            "inspection_window_bp", sa.Integer(), server_default=sa.text("20000"), nullable=False
        ),
        sa.Column("available_bp", sa.Integer(), nullable=False),
        sa.Column("inspected_bp", sa.Integer(), nullable=False),
        sa.Column("assessment_policy_key", sa.String(length=255), nullable=False),
        sa.Column("method_or_curator_key", sa.String(length=255), nullable=False),
        sa.Column("evidence_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("evidence_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "side IN ('left', 'right')", name=op.f("ck_flank_assessment_valid_side")
        ),
        sa.CheckConstraint(
            "verdict <> 'supported' OR inspected_bp > 0",
            name=op.f("ck_flank_assessment_supported_has_inspected_sequence"),
        ),
        sa.CheckConstraint(
            "verdict IN ('supported', 'contradicted', 'insufficient', 'not_assessed')",
            name=op.f("ck_flank_assessment_valid_verdict"),
        ),
        sa.CheckConstraint(
            "available_bp >= 0", name=op.f("ck_flank_assessment_nonnegative_available")
        ),
        sa.CheckConstraint(
            "inspected_bp >= 0 AND inspected_bp <= available_bp",
            name=op.f("ck_flank_assessment_valid_inspected_length"),
        ),
        sa.CheckConstraint(
            "inspection_window_bp > 0", name=op.f("ck_flank_assessment_positive_window")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_flank_assessment_evidence_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["placement_id", "release_id", "locus_id"],
            [
                "eve_locus_placement.id",
                "eve_locus_placement.release_id",
                "eve_locus_placement.locus_id",
            ],
            name="fk_flank_assessment_placement_same_locus",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flank_assessment")),
        sa.UniqueConstraint("assessment_key", name=op.f("uq_flank_assessment_assessment_key")),
        sa.UniqueConstraint(
            "id",
            "release_id",
            "locus_id",
            "placement_id",
            "side",
            "verdict",
            name="uq_flank_assessment_membership_ref",
        ),
        sa.UniqueConstraint(
            "release_id",
            "locus_id",
            "placement_id",
            "side",
            "assessment_policy_key",
            name="uq_flank_assessment_policy_side",
        ),
    )
    op.create_table(
        "import_ledger",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("source_record_id", sa.BigInteger(), nullable=False),
        sa.Column("call_id", sa.BigInteger(), nullable=True),
        sa.Column("locus_id", sa.BigInteger(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("result_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome <> 'normalized_candidate' OR (call_id IS NOT NULL AND locus_id IS NOT NULL)",
            name=op.f("ck_import_ledger_candidate_has_call_and_locus"),
        ),
        sa.CheckConstraint(
            "outcome IN ('normalized_candidate', 'review', 'quarantine', 'exclude')",
            name=op.f("ck_import_ledger_valid_outcome"),
        ),
        sa.CheckConstraint(
            "result_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_import_ledger_valid_result_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "call_id"],
            ["detection_call.release_id", "detection_call.id"],
            name="fk_import_ledger_call_same_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "locus_id"],
            ["eve_locus.release_id", "eve_locus.id"],
            name="fk_import_ledger_locus_same_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "release_id"],
            ["import_run.id", "import_run.release_id"],
            name="fk_import_ledger_run_same_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_record.id"],
            name=op.f("fk_import_ledger_source_record_id_source_record"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_ledger")),
        sa.UniqueConstraint(
            "id", "release_id", "locus_id", "outcome", name="uq_import_ledger_decision_ref"
        ),
        sa.UniqueConstraint("run_id", "source_record_id", name="uq_import_ledger_run_record"),
    )
    op.create_table(
        "source_assessment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assessment_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("call_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "assessment_type",
            sa.String(length=32),
            server_default=sa.text("'hcvr'"),
            nullable=False,
        ),
        sa.Column("source_label", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("source_artifact_id", sa.BigInteger(), nullable=False),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(source_label = 'Yes' AND confidence = 'source_high') OR "
            "(source_label <> 'Yes' AND confidence = 'source_low')",
            name=op.f("ck_source_assessment_label_maps_to_confidence"),
        ),
        sa.CheckConstraint(
            "assessment_type = 'hcvr'", name=op.f("ck_source_assessment_only_hcvr_assessment")
        ),
        sa.CheckConstraint(
            "confidence IN ('source_high', 'source_low')",
            name=op.f("ck_source_assessment_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "call_id"],
            ["detection_call.release_id", "detection_call.id"],
            name="fk_source_assessment_call_same_release",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_source_assessment_source_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_assessment")),
        sa.UniqueConstraint("assessment_key", name=op.f("uq_source_assessment_assessment_key")),
        sa.UniqueConstraint(
            "release_id", "call_id", "assessment_type", name="uq_source_assessment_call_type"
        ),
    )
    op.create_table(
        "inclusion_decision",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("decision_key", sa.String(length=255), nullable=False),
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("locus_id", sa.BigInteger(), nullable=False),
        sa.Column("placement_id", sa.BigInteger(), nullable=True),
        sa.Column("import_ledger_id", sa.BigInteger(), nullable=False),
        sa.Column("import_outcome", sa.String(length=32), nullable=False),
        sa.Column("decision_code", sa.String(length=32), nullable=False),
        sa.Column("policy_key", sa.String(length=255), nullable=False),
        sa.Column("authorized_by", sa.String(length=255), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision_code <> 'include' OR import_outcome = 'normalized_candidate'",
            name=op.f("ck_inclusion_decision_include_has_normalized_import"),
        ),
        sa.CheckConstraint(
            "decision_code <> 'include' OR placement_id IS NOT NULL",
            name=op.f("ck_inclusion_decision_include_has_placement"),
        ),
        sa.CheckConstraint(
            "decision_code IN ('include', 'review', 'quarantine', 'exclude')",
            name=op.f("ck_inclusion_decision_valid_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["import_ledger_id", "release_id", "locus_id", "import_outcome"],
            [
                "import_ledger.id",
                "import_ledger.release_id",
                "import_ledger.locus_id",
                "import_ledger.outcome",
            ],
            name="fk_inclusion_decision_import_outcome",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["placement_id", "release_id", "locus_id"],
            [
                "eve_locus_placement.id",
                "eve_locus_placement.release_id",
                "eve_locus_placement.locus_id",
            ],
            name="fk_inclusion_decision_placement_same_locus",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "locus_id"],
            ["eve_locus.release_id", "eve_locus.id"],
            name="fk_inclusion_decision_locus_same_release",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inclusion_decision")),
        sa.UniqueConstraint("decision_key", name=op.f("uq_inclusion_decision_decision_key")),
        sa.UniqueConstraint(
            "id",
            "release_id",
            "locus_id",
            "decision_code",
            "placement_id",
            name="uq_inclusion_decision_membership_ref",
        ),
        sa.UniqueConstraint(
            "release_id", "locus_id", "policy_key", name="uq_inclusion_decision_policy"
        ),
    )
    op.create_table(
        "quarantine_issue",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("issue_key", sa.String(length=255), nullable=False),
        sa.Column("ledger_id", sa.BigInteger(), nullable=False),
        sa.Column("issue_code", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('error', 'warning')", name=op.f("ck_quarantine_issue_valid_severity")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'waived')",
            name=op.f("ck_quarantine_issue_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ledger_id"],
            ["import_ledger.id"],
            name=op.f("fk_quarantine_issue_ledger_id_import_ledger"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantine_issue")),
        sa.UniqueConstraint("issue_key", name=op.f("uq_quarantine_issue_issue_key")),
    )
    op.create_table(
        "release_locus_membership",
        sa.Column("release_id", sa.BigInteger(), nullable=False),
        sa.Column("locus_id", sa.BigInteger(), nullable=False),
        sa.Column("placement_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "placement_precision",
            sa.String(length=16),
            server_default=sa.text("'exact'"),
            nullable=False,
        ),
        sa.Column("inclusion_decision_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "decision_code",
            sa.String(length=32),
            server_default=sa.text("'include'"),
            nullable=False,
        ),
        sa.Column("left_flank_assessment_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "left_flank_side",
            sa.String(length=16),
            server_default=sa.text("'left'"),
            nullable=False,
        ),
        sa.Column(
            "left_flank_verdict",
            sa.String(length=32),
            server_default=sa.text("'supported'"),
            nullable=False,
        ),
        sa.Column("right_flank_assessment_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "right_flank_side",
            sa.String(length=16),
            server_default=sa.text("'right'"),
            nullable=False,
        ),
        sa.Column(
            "right_flank_verdict",
            sa.String(length=32),
            server_default=sa.text("'supported'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision_code = 'include'",
            name=op.f("ck_release_locus_membership_requires_include_decision"),
        ),
        sa.CheckConstraint(
            "left_flank_side = 'left' AND left_flank_verdict = 'supported'",
            name=op.f("ck_release_locus_membership_requires_supported_left_flank"),
        ),
        sa.CheckConstraint(
            "placement_precision = 'exact'",
            name=op.f("ck_release_locus_membership_requires_exact_placement"),
        ),
        sa.CheckConstraint(
            "right_flank_side = 'right' AND right_flank_verdict = 'supported'",
            name=op.f("ck_release_locus_membership_requires_supported_right_flank"),
        ),
        sa.CheckConstraint(
            "left_flank_assessment_id <> right_flank_assessment_id",
            name=op.f("ck_release_locus_membership_distinct_flank_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["inclusion_decision_id", "release_id", "locus_id", "decision_code", "placement_id"],
            [
                "inclusion_decision.id",
                "inclusion_decision.release_id",
                "inclusion_decision.locus_id",
                "inclusion_decision.decision_code",
                "inclusion_decision.placement_id",
            ],
            name="fk_release_locus_membership_include_decision",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "left_flank_assessment_id",
                "release_id",
                "locus_id",
                "placement_id",
                "left_flank_side",
                "left_flank_verdict",
            ],
            [
                "flank_assessment.id",
                "flank_assessment.release_id",
                "flank_assessment.locus_id",
                "flank_assessment.placement_id",
                "flank_assessment.side",
                "flank_assessment.verdict",
            ],
            name="fk_release_locus_membership_left_flank",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["placement_id", "release_id", "locus_id", "placement_precision"],
            [
                "eve_locus_placement.id",
                "eve_locus_placement.release_id",
                "eve_locus_placement.locus_id",
                "eve_locus_placement.precision",
            ],
            name="fk_release_locus_membership_exact_placement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id", "locus_id"],
            ["eve_locus.release_id", "eve_locus.id"],
            name="fk_release_locus_membership_locus",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "right_flank_assessment_id",
                "release_id",
                "locus_id",
                "placement_id",
                "right_flank_side",
                "right_flank_verdict",
            ],
            [
                "flank_assessment.id",
                "flank_assessment.release_id",
                "flank_assessment.locus_id",
                "flank_assessment.placement_id",
                "flank_assessment.side",
                "flank_assessment.verdict",
            ],
            name="fk_release_locus_membership_right_flank",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("release_id", "locus_id", name=op.f("pk_release_locus_membership")),
    )

    # CHECK constraints cannot compare a placement against its parent sequence length.
    op.execute(
        """
        CREATE FUNCTION eve_check_placement_bounds()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            expected_assembly_id bigint;
            expected_sequence_length bigint;
        BEGIN
            SELECT assembly_id, sequence_length
              INTO expected_assembly_id, expected_sequence_length
              FROM assembly_sequence
             WHERE id = NEW.sequence_id;

            IF NOT FOUND
               OR expected_assembly_id <> NEW.assembly_id
               OR NEW.end0 > expected_sequence_length THEN
                RAISE EXCEPTION
                    'placement % is outside sequence % or uses the wrong assembly',
                    NEW.placement_key,
                    NEW.sequence_id
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'ck_eve_locus_placement_within_sequence';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_eve_locus_placement_bounds
        BEFORE INSERT OR UPDATE OF assembly_id, sequence_id, start0, end0
        ON eve_locus_placement
        FOR EACH ROW EXECUTE FUNCTION eve_check_placement_bounds()
        """
    )

    # A quarantine terminal outcome is never allowed to exist without a structured issue.
    op.execute(
        """
        CREATE FUNCTION eve_require_quarantine_issue()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.outcome = 'quarantine'
               AND NOT EXISTS (
                   SELECT 1 FROM quarantine_issue WHERE ledger_id = NEW.id
               ) THEN
                RAISE EXCEPTION
                    'quarantine ledger entry % has no quarantine issue', NEW.id
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'ck_import_ledger_quarantine_has_issue';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_import_ledger_quarantine_issue
        AFTER INSERT OR UPDATE ON import_ledger
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION eve_require_quarantine_issue()
        """
    )
    op.execute(
        """
        CREATE FUNCTION eve_preserve_quarantine_issue()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                   SELECT 1
                     FROM import_ledger
                    WHERE id = OLD.ledger_id AND outcome = 'quarantine'
               )
               AND NOT EXISTS (
                   SELECT 1 FROM quarantine_issue WHERE ledger_id = OLD.ledger_id
               ) THEN
                RAISE EXCEPTION
                    'cannot remove the last issue from quarantine ledger entry %', OLD.ledger_id
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'ck_import_ledger_quarantine_has_issue';
            END IF;
            RETURN OLD;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_quarantine_issue_preserved
        AFTER DELETE OR UPDATE ON quarantine_issue
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION eve_preserve_quarantine_issue()
        """
    )

    # Once a release is public or deprecated, its release-scoped rows are append-closed.
    op.execute(
        """
        CREATE FUNCTION eve_block_published_release_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            old_release_id bigint;
            new_release_id bigint;
        BEGIN
            old_release_id := CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.release_id END;
            new_release_id := CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE NEW.release_id END;
            IF EXISTS (
                SELECT 1
                  FROM dataset_release
                 WHERE id IN (old_release_id, new_release_id)
                   AND status IN ('published', 'deprecated')
            ) THEN
                RAISE EXCEPTION
                    'published/deprecated release-scoped rows are immutable'
                    USING ERRCODE = '55000';
            END IF;
            RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$
        """
    )
    for table_name in RELEASE_SCOPED_TABLES:
        op.execute(
            sa.text(
                f"CREATE TRIGGER trg_{table_name}_published_immutable "
                f"BEFORE INSERT OR UPDATE OR DELETE ON {table_name} "
                "FOR EACH ROW EXECUTE FUNCTION eve_block_published_release_mutation()"
            )
        )

    # The release row itself is immutable after publication.  Deprecation is the sole
    # status-only transition; all identity, manifest and timestamp fields remain frozen.
    op.execute(
        """
        CREATE FUNCTION eve_guard_dataset_release_lifecycle()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'INSERT' AND NEW.status <> 'candidate' THEN
                RAISE EXCEPTION 'new releases must start as candidate'
                    USING ERRCODE = '23514';
            ELSIF TG_OP = 'DELETE' AND OLD.status IN ('published', 'deprecated') THEN
                RAISE EXCEPTION 'published/deprecated release rows cannot be deleted'
                    USING ERRCODE = '55000';
            ELSIF TG_OP = 'UPDATE' THEN
                IF OLD.status = 'deprecated' THEN
                    RAISE EXCEPTION 'deprecated release rows are immutable'
                        USING ERRCODE = '55000';
                ELSIF OLD.status = 'published' THEN
                    IF NEW.status <> 'deprecated'
                       OR ROW(
                           NEW.id,
                           NEW.dataset_id,
                           NEW.release_key,
                           NEW.schema_version,
                           NEW.manifest_sha256,
                           NEW.published_at,
                           NEW.supersedes_release_id,
                           NEW.created_at
                       ) IS DISTINCT FROM ROW(
                           OLD.id,
                           OLD.dataset_id,
                           OLD.release_key,
                           OLD.schema_version,
                           OLD.manifest_sha256,
                           OLD.published_at,
                           OLD.supersedes_release_id,
                           OLD.created_at
                       ) THEN
                        RAISE EXCEPTION
                            'published release content is immutable; only deprecation is allowed'
                            USING ERRCODE = '55000';
                    END IF;
                ELSIF NEW.status = 'published' AND OLD.status <> 'validated' THEN
                    RAISE EXCEPTION 'only a validated release can be published'
                        USING ERRCODE = '23514';
                ELSIF NEW.status = 'deprecated' THEN
                    RAISE EXCEPTION 'only a published release can be deprecated'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_dataset_release_lifecycle
        BEFORE INSERT OR UPDATE OR DELETE ON dataset_release
        FOR EACH ROW EXECUTE FUNCTION eve_guard_dataset_release_lifecycle()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_locus_membership")
    op.drop_table("quarantine_issue")
    op.drop_table("inclusion_decision")
    op.drop_table("source_assessment")
    op.drop_table("import_ledger")
    op.drop_table("flank_assessment")
    op.drop_index(
        "ix_eve_locus_placement_exact_interval",
        table_name="eve_locus_placement",
        postgresql_where=sa.text("precision = 'exact'"),
    )
    op.drop_table("eve_locus_placement")
    op.drop_table("detection_call")
    op.drop_table("lineage_closure")
    op.drop_table("lineage_alias")
    op.drop_table("eve_locus")
    op.drop_table("assembly_taxon_assignment")
    op.drop_table("release_lineage_snapshot")
    op.drop_table("release_assembly_membership")
    op.drop_table("lineage_term")
    op.drop_table("import_run")
    op.drop_table("assembly_sequence")
    op.drop_table("source_record")
    op.drop_table("release_source_snapshot")
    op.drop_table("lineage_snapshot")
    op.drop_table("genome_assembly")
    op.drop_table("source_artifact")
    op.drop_table("dataset_release")
    op.drop_table("source_snapshot")
    op.drop_table("dataset")
    op.execute("DROP FUNCTION IF EXISTS eve_guard_dataset_release_lifecycle()")
    op.execute("DROP FUNCTION IF EXISTS eve_block_published_release_mutation()")
    op.execute("DROP FUNCTION IF EXISTS eve_preserve_quarantine_issue()")
    op.execute("DROP FUNCTION IF EXISTS eve_require_quarantine_issue()")
    op.execute("DROP FUNCTION IF EXISTS eve_check_placement_bounds()")
    # ### end Alembic commands ###
